typography_spectrum: 0.9381286751013249
color:
  brandStrength: 0.23018433549441397
  lightness: 0.19370294245891273
  saturation: 0.38541526487097144
  rhythmicContrast: 0.9323733511846513
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
layout_spectrum: 0.3610581473913044
author:
  name: Steve Noble
  email: noblesteve@msn.com
name: Steve Noble
title: STEVE NOBLE
description: '"Video Killed Radio"'
navigation:
  - name: Man in The High Castle
    url: 'http://www.imdb.com/title/tt1740299/'
    type: external
