author:
  name: Steve Noble
  email: noblesteve@msn.com
color:
  saturation: 0.3854152648709714
  brandStrength: 0.230184335494414
  rhythmicContrast: 0.9323733511846513
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  lightness: 0.1937029424589127
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: STEVE NOBLE
layout_spectrum: 0.3610581473913044
typography_spectrum: 0.3012889
description: '"Video killed Radio"'
name: Steve Noble
